### ISSUE TITLE
About vote validation acc.

### ISSUE THREAD

**Issue by junshengzhou** [lulutang0608/Point-BERT#16]
Hi. Thank you for your great work.

Did other works(eg. PointTransformer) use the same **voting** strategy? It seems like the results reported on the paper is vote validation acc.

**Comment by yuxumin** [comment]
Hi,
1) Sorry that i don't know whether PointTransformer has adopted voting strategy or not, since the source code of this work are not open yet.  
2) We report the voting acc for PointBERT in our paper, followed [PointNet/PointNet++](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/test_classification.py#L47), [DGCNN](https://github.com/WangYueFt/dgcnn/blob/e96a7e26555c3212dbc5df8d8875f07228e1ccc2/tensorflow/evaluate.py#L119) and [RSCNN](https://github.com/Yochengliu/Relation-Shape-CNN/blob/master/voting_evaluate_cls.py#L79)

**Comment by junshengzhou** [comment]
OK. Thank you for your reply!
