### ISSUE TITLE
Confusion about the Point Tokenizer

### ISSUE THREAD

**Issue by auniquesun** [lulutang0608/Point-BERT#28]
@yuxumin @lulutang0608 @raoyongming Thanks for sharing the paper and code.

One point I am confused with is the `Point Tokenizer` in the framework.

According to the paper and my understanding, the farthest point sampling (FPS) produces _g_ centers, after that kNN is used such that there are _g_ groups, then you adopt the mini-PointNet to extract featues of previous _g_ groups and the output can be treated as an input sequence to standard Transformer.

Immediately after that, however, you give a small section on `Point Tokenizer`, it actually is a DGCNN. My question is what's the utility of `Point Tokenizer` and why need to tokenize embeddings since the input sequences have been created and the inner embeddings are inherently separated by FPS according to previous `Point Embeddings`. 

Is `Point Tokenizer` necessary in the framework?

**Comment by lulutang0608** [comment]
Thanks for being interested in our work. As for Point Tokenizer, which is used to generate the self-supervised signals for pre-training Transformer. More specifically, the Transformer's input is the input sequences (as you know), and the Transformer's output is the self-generated point tokens.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jerry Sun ***@***.***>
发送时间: Sunday, April 3, 2022 5:21:07 PM
收件人: lulutang0608/Point-BERT ***@***.***>
抄送: Lulu Tang ***@***.***>; Mention ***@***.***>
主题: [lulutang0608/Point-BERT] Confusion about the Point Tokenizer (Issue #28)


@yuxumin<https://github.com/yuxumin> @lulutang0608<https://github.com/lulutang0608> @raoyongming<https://github.com/raoyongming> Thanks for sharing the paper and code.

One point I am confused with is the Point Tokenizer in the framework.

According to the paper and my understanding, the farthest point sampling produces g centers, after that kNN is used such that there are g groups, then you adopt the mini-PointNet to extract featues of previous g groups and the output can be treated as an input sequence to standart Transformer.

Immediately after that, however, you give a small section on Point Tokenizer. My question is what's the utility of Point Tokenizer and why is it neccessary since the input sequences have been ready according to previous Point Embeddings.

―

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
