### ISSUE TITLE
how to test the Few-shot classification  and what is the "--fold"

### ISSUE THREAD

**Issue by TangYuan96** [lulutang0608/Point-BERT#36]
Hi, first of all, thank you for sharing the excellent work.

1. I would like to ask, how to test few-shot learning? It seems that there are only train and validate codes for few-shot learning?

2. I want to ask the meaning of the "--fold" parameter

**Comment by yuxumin** [comment]
Thanks for your interest in our work.
1. The dataset is not an online benchmark or competition. So the validation codes are just test codes
2. Because of the small scale of the dataset for few-shot-learning setting. We conduct 10 independent experiments under each setting and the mean and standard deviation over 10 runs are reported. We randomly split the data into 10 situation, and use `fold` to indicate the index of those situations. (Similiar to the `fold` in cross-validation)

**Comment by yuxumin** [comment]
Thanks for your interest in our work.
1. The dataset is not an online benchmark or competition. So the validation codes are just test codes
2. Because of the small scale of the dataset for few-shot-learning setting. We conduct 10 independent experiments under each setting and the mean and standard deviation over 10 runs are reported. We randomly split the data into 10 situation, and use `fold` to indicate the index of those situations. (Similiar to the `fold` in cross-validation)

**Comment by TangYuan96** [comment]
Are the steps like this?

1. Use 10 situations, train separately
2. Get 10 verifications
3. Take their mean and variance as the results in Table 2?

**Comment by yuxumin** [comment]
1) Yes
2) no voting strategy used in this setting.

**Comment by TangYuan96** [comment]
But the process of few-shot learning will go through validate_vote() in the file (runner_BERT_finetune.py).

Do we use  the output of validate() as the result of table 2?

**Comment by rabbit218218** [comment]
Why am I getting the following error when using ModelNetFewShot?

.../runner_pretrain.py", line 143, in run_net  
    raise NotImplementedError(f'Train phase does not support {dataset_name}')
NotImplementedError: Train phase does not support ModelNetFewShot
